{% set version = "0.16" %}

package:
  name: otfmi
  version: {{ version }}

source:
  fn: otfmi-{{ version }}.tar.gz
  url: https://github.com/openturns/otfmi/archive/v{{ version }}.tar.gz
  sha256: 5a1d23362f97da34117026662f73ae1405e3bbe92e2d1c01f8b68f33d157f0c3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.6
    - openturns
    - pyfmi
    - assimulo >=3.0
    - pythonfmu
    - jinja2
    - dill

test:
  imports:
    - otfmi

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: FMI models manipulation module

extra:
  recipe-maintainers:
    - jschueller
