{% set version = "0.3" %}


package:
  name: otfmi
  version: {{ version }}

source:
  fn: otfmi-{{ version }}.tar.gz
  url: https://github.com/openturns/otfmi/archive/v{{ version }}.tar.gz
  sha256: 0169e8b4ada95c57f6250b60849b588e9e476453b0bf76eb42e414b6f8c49918

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python
    - openturns
    - pyfmi
    - assimulo >=3.0

test:
  imports:
    - otfmi

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER
  summary: FMI models manipulation module

extra:
  recipe-maintainers:
    - jschueller
