{% set version = "0.6" %}

package:
  name: otfmi
  version: {{ version }}

source:
  fn: otfmi-{{ version }}.tar.gz
  url: https://github.com/openturns/otfmi/archive/v{{ version }}.tar.gz
  sha256: 34a06bc65a40eab5d9aef9bcc02654f46f3e9ead23c839fd411b2c84a5096004

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.6
    - openturns 1.16*
    - pyfmi
    - assimulo >=3.0

test:
  imports:
    - otfmi

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: FMI models manipulation module

extra:
  recipe-maintainers:
    - jschueller
